# =============================================================
# DragonBallLegends Offline - Single Mode
# =============================================================
server.sv               = 1
server.name             = DragonBallLegends Offline
server.local            = false
server.test             = false
server.daoautoupdater   = false
server.debug            = false

server.ip_host          = 127.0.0.1
server.port_real        = 14445
server.port_proxy       = 14446
server.sv1              = Offline:127.0.0.1:14445:0,0,0

database.driver         = com.mysql.jdbc.Driver
database.host           = 127.0.0.1
database.port           = 3307
database.name           = nroserver
database.user           = root
database.pass           =
database.min            = 1
database.max            = 10
database.lifetime       = 120000

server.waitlogin        = 1
server.maxperip         = 10
server.maxplayer        = 100
server.expserver        = 1

auto.maintenance        = 0
auto.maintenance.hour   = 8
auto.maintenance.minute = 30

event.year              = 2026

event.top.month_open    = 1
event.top.date_open     = 1
event.top.hour_open     = 0
event.top.minute_open   = 0
event.top.month_end     = 12
event.top.date_end      = 31
event.top.hour_end      = 23
event.top.minute_end    = 59
event.top.month_reward  = 12
event.top.date_reward   = 31
event.top.hour_reward   = 23
event.top.minute_reward = 59

event.sm.month_open     = 1
event.sm.date_open      = 1
event.sm.hour_open      = 0
event.sm.minute_open    = 0
event.sm.month_end      = 12
event.sm.date_end       = 31
event.sm.hour_end       = 23
event.sm.minute_end     = 59

event.nap.month_open    = 1
event.nap.date_open     = 1
event.nap.hour_open     = 0
event.nap.minute_open   = 0
event.nap.month_end     = 12
event.nap.date_end      = 31
event.nap.hour_end      = 23
event.nap.minute_end    = 59

event.chucvip.month_open  = 1
event.chucvip.date_open   = 1
event.chucvip.hour_open   = 0
event.chucvip.minute_open = 0
event.chucvip.month_end   = 12
event.chucvip.date_end    = 31
event.chucvip.hour_end    = 23
event.chucvip.minute_end  = 59

event.trangsucvip.month_open  = 1
event.trangsucvip.date_open   = 1
event.trangsucvip.hour_open   = 0
event.trangsucvip.minute_open = 0
event.trangsucvip.month_end   = 12
event.trangsucvip.date_end    = 31
event.trangsucvip.hour_end    = 23
event.trangsucvip.minute_end  = 59

event.thangmuoi.month_open    = 1
event.thangmuoi.date_open     = 1
event.thangmuoi.hour_open     = 0
event.thangmuoi.minute_open   = 0
event.thangmuoi.month_end     = 12
event.thangmuoi.date_end      = 31
event.thangmuoi.hour_end      = 23
event.thangmuoi.minute_end    = 59
